/**
 * Reproducible game build:
 *   1. Read the studio-generated content pack (content/pack.json)
 *   2. Validate it
 *   3. Bundle the browser client with esbuild (deterministic flags)
 *   4. Emit dist/content.js (the pack as an embeddable script)
 *   5. Copy web/index.html
 *   6. Write manifest with checksums (build-info.json)
 *
 * Same inputs ⇒ byte-identical outputs (esbuild is deterministic; the only
 * timestamp lives outside hashed artifacts).
 */
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { fnv1a } from "../src/engine/core/hash.js";
import { validateContentPack } from "../src/engine/content/types.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const distDir = join(root, "dist");

function main(): void {
  const packPath = join(root, "content", "pack.json");
  const packJson = readFileSync(packPath, "utf8");
  const pack = JSON.parse(packJson);

  const problems = validateContentPack(pack);
  if (problems.length > 0) {
    console.error("BUILD FAILED — invalid content pack:");
    for (const p of problems) console.error(" -", p);
    process.exit(1);
  }

  mkdirSync(distDir, { recursive: true });

  // Content as an embeddable script (works over file:// too).
  const contentJs =
    `/* Generated by ai-game-studio build. Pack checksum ${fnv1a(stablePackString(pack))}. */\n` +
    `window.CONTENT_PACK = ${JSON.stringify(pack)};\n`;
  writeFileSync(join(distDir, "content.js"), contentJs);
  writeFileSync(join(distDir, "pack.json"), JSON.stringify(pack, null, 2));

  void build({
    entryPoints: [join(root, "src", "client", "main.ts")],
    bundle: true,
    minify: true,
    sourcemap: false,
    format: "iife",
    target: ["es2020"],
    outfile: join(distDir, "game.js"),
    logLevel: "warning",
    define: { "process.env.NODE_ENV": '"production"' },
  })
    .then(() => {
      copyFileSync(join(root, "web", "index.html"), join(distDir, "index.html"));

      const files = ["game.js", "content.js", "index.html", "pack.json"];
      const manifest: Record<string, unknown> = {
        title: pack.meta?.title,
        version: pack.meta?.version,
        generator: pack.meta?.generator,
        builtWith: "ai-game-studio",
        files: {} as Record<string, string>,
      };
      const f = manifest.files as Record<string, string>;
      for (const name of files) {
        const data = readFileSync(join(distDir, name));
        f[name] = `${data.length.toString(16).padStart(8, "0")}${fnv1a(data.toString("latin1"))}`;
      }
      writeFileSync(join(distDir, "build-info.json"), JSON.stringify(manifest, null, 2));
      console.log(`Build OK → dist/ (${manifest.files ? Object.keys(f).length : 0} artifacts, pack v${pack.meta.version})`);
    })
    .catch((err) => {
      console.error("esbuild failed:", err);
      process.exit(1);
    });
}

/** Deterministic stringify for the pack checksum. */
function stablePackString(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value) ?? "null";
  if (Array.isArray(value)) return `[${value.map(stablePackString).join(",")}]`;
  const entries = Object.entries(value as Record<string, unknown>);
  entries.sort(([a], [b]) => (a < b ? -1 : 1));
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${stablePackString(v)}`).join(",")}}`;
}

main();
